name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.6"

      - name: Install Flutter dependencies
        run: flutter pub get
        working-directory: soluva

      - name: Create temporary .env
        run: |
          echo "BASE_URL=${{ secrets.ENV_API_URL }}" >> soluva/.env
          echo "ENV_DEBUG=${{ secrets.ENV_OTHER_KEY }}" >> soluva/.env

      - name: Build Flutter Web
        run: flutter build web --release
        working-directory: soluva

      - name: Deploy via FTP/FTPS
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: 21
          protocol: ftps
          local-dir: soluva/build/web/
          server-dir: / # sube directo al public_html

      - name: Deployment completed
        run: echo "Deploy completed at $(date)"
